import type { Inputs } from './model'

export const DEFAULT_INPUTS: Inputs = {
  personal: { grossSalary: 20000, creditPoints: 2.25, kmPerYear: 20000, altReturnPct: 4, horizonYears: 5 },
  reimb: { maintenanceGross: 2000, travelGross: 300, employerDepositsPct: 0 },
  company: {
    listPrice: 180000,
    propulsion: 'hybrid',
    participation: 0,
    fuelMode: 'full',
    fuelCap: 800,
    fuelBenefitGross: 0,
    employerGrossUp: false,
    kmPerUnit: 18,
    energyPrice: 7.3,
    allowedKmPerYear: 30000,
    extraKmPrice: 0.5,
    otherMonthly: 0,
  },
  existing: {
    enabled: true,
    keepWithCompanyCar: false,
    value: 70000,
    depreciationPct: 10,
    insuranceYear: 6000,
    licenseYear: 1500,
    maintenanceYear: 3500,
    maintenanceGrowthPct: 8,
    kmPerUnit: 14,
    energyPrice: 7.3,
    otherMonthly: 0,
  },
  used: {
    enabled: true,
    value: 90000,
    depreciationPct: 12,
    insuranceYear: 5500,
    licenseYear: 1400,
    maintenanceYear: 3000,
    maintenanceGrowthPct: 8,
    kmPerUnit: 15,
    energyPrice: 7.3,
    otherMonthly: 0,
    purchaseCosts: 2000,
    financing: 'cash',
    downPayment: 30000,
    loanRatePct: 7,
    loanMonths: 60,
  },
}
